os: osx
osx_image: xcode9.3
script:
  - xcodebuild -version
  - set -o pipefail && env "NSUnbufferedIO=YES" xcodebuild test -scheme CloudKitCodable -project CloudKitCodable.xcodeproj | xcpretty -f `xcpretty-travis-formatter`